version: '2'

services:
  django: &django
    build: .
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    command: 'uwsgi -c /app/conf/uwsgi.ini'

  # reuse the same config as the django container but with a different command
  # this eliminates the need to install all dependencies in two containers
  celery:
    <<: *django
    depends_on:
      - redis
      - db
    command: 'celery -A server worker --loglevel INFO'
    # this is a bit counter-intuitive, but we can just always use the prod config for celery since
    # otherwise it'll look for redis at localhost
    environment:
      DJANGO_SETTINGS_MODULE: 'server.settings_prod'

  redis:
    image: 'redis'

  db:
    image: 'postgres'

  nginx:
    image: nginx
    depends_on:
      - django
    links:
      - django
    volumes:
      - './conf/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './conf/uwsgi_params:/etc/nginx/uwsgi_params:ro'
    ports:
      - 8000:8000
