version: '3.1'

services:
  django: &django
    build: .
    image: do.vinn.ie:5000/csci_tool
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    command: 'uwsgi -c /app/conf/uwsgi.ini'
    # this is a bit counter-intuitive, but we can just always use the prod config and override it
    # locally for development. this helps with making deployment easier
    environment:
      DJANGO_SETTINGS_MODULE: 'server.settings_prod'
    secrets:
      - db_password
      - django_secret

  # reuse the same config as the django container but with a different command
  # this eliminates the need to install all dependencies in two containers
  celery:
    <<: *django
    depends_on:
      - redis
      - db
    command: 'celery -A server worker --loglevel INFO'

  redis:
    image: 'redis'

  db:
    image: 'postgres'
    environment:
      POSTGRES_USER: 'csci_tool'
      POSTGRES_PASSWORD_FILE: '/run/secrets/db_password'
      POSTGRES_DB: 'csci_tool'
    secrets:
      - db_password
      - django_secret

  nginx:
    image: nginx
    depends_on:
      - django
    links:
      - django
    volumes:
      - './conf/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './conf/uwsgi_params:/etc/nginx/uwsgi_params:ro'
      - './static/:/usr/share/nginx/django_static:ro'
    ports:
      - 8000:8000


secrets:
  db_password:
    external: true
  django_secret:
    external: true
