# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('path', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('due_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('sha', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('commit_date', models.DateTimeField()),
                ('push_date', models.DateTimeField()),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usc_email', models.EmailField(max_length=254, unique=True)),
                ('usc_id', models.CharField(max_length=20, unique=True)),
                ('github_username', models.CharField(max_length=100)),
                ('preferred_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('late_days_used', models.IntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitbot.Assignment')),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitbot.Commit')),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gitbot.Student')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitbot.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set([('student', 'assignment', 'commit')]),
        ),
        migrations.AddField(
            model_name='commit',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitbot.Repo'),
        ),
    ]
