# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 19:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(editable=False, max_length=100)),
                ('due_date', models.DateTimeField(editable=False, null=True)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('sha', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('commit_date', models.DateTimeField()),
                ('push_date', models.DateTimeField()),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitbot.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Mutation',
            fields=[
                ('sha', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitbot.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usc_email', models.EmailField(max_length=254)),
                ('usc_id', models.CharField(max_length=20)),
                ('github_username', models.CharField(max_length=100)),
                ('preferred_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('canary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('late_days_used', models.IntegerField(default=0)),
                ('grades', models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitbot.Assignment')),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitbot.Commit')),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gitbot.Student')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitbot.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitbot.Course'),
        ),
        migrations.AddField(
            model_name='mutation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitbot.Student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitbot.Course'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set([('student', 'assignment', 'commit')]),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set([('course', 'usc_id'), ('course', 'usc_email'), ('course', 'github_username')]),
        ),
        migrations.AlterUniqueTogether(
            name='coursesetting',
            unique_together=set([('course', 'key')]),
        ),
        migrations.AddField(
            model_name='commit',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitbot.Repo'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set([('course', 'path')]),
        ),
        migrations.AlterUniqueTogether(
            name='commit',
            unique_together=set([('repo', 'sha')]),
        ),
    ]
