# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='github_username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
