# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitbot', '0002_student_github_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo',
            old_name='repo_name',
            new_name='name',
        ),
    ]
