# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 17:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('gitbot', '0003_student_canary'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grades',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='path',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
