# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitbot', '0003_auto_20170920_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='sha',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
