# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitbot', '0004_auto_20170924_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mutation',
            fields=[
                ('sha', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitbot.Assignment')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitbot.Repo')),
            ],
        ),
    ]
