# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitbot', '0004_commit_sha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='usc_id',
            field=models.CharField(max_length=20),
        ),
    ]
