# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitbot', '0005_mutation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutation',
            name='repo',
        ),
        migrations.AddField(
            model_name='mutation',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gitbot.Student'),
            preserve_default=False,
        ),
    ]
