# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitbot', '0007_auto_20170921_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitbot.Assignment')),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitbot.Commit')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitbot.Student')),
            ],
        ),
    ]
