# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitbot', '0008_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assigned_date',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='name',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='path',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
