# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitbot', '0009_auto_20170921_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='usc_email',
            field=models.EmailField(max_length=254),
        ),
    ]
